config/routes.rb
Rails.application.routes.draw do
  get 'loan/index'

  resources :loans
  

end

app/models/loan.rb
class Loan < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
  	@loans = Loan.all
  end
  def new
  	@loan = Loan.new
  end
  def show
  	@loan = Loan.find(params[:id])
  	loan_action
  end
  def create
  	@loan = Loan.new(loan_params)
		if @loan.save
			redirect_to @loan
		else
			render 'new'
		end
  end
  def edit
	@loan = Loan.find(params[:id])
  end
  def update
	@loan = Loan.find(params[:id])
	 
	if @loan.update(loan_params)
		redirect_to @loan
	else
		render 'edit'
  	end
  end
  def destroy
		@loan = Loan.find(params[:id])
		@loan.destroy

		redirect_to loans_path
	end
  def loan_action
  	@amount = Integer(@loan.amount)
  	@year = Integer(@loan.year)
  	@interest = Float(@loan.interest)
	monthly_interest = @interest / (12 * 100)
	
	@total_month = @year * 12
	math_pow_value = 1 - (1 + monthly_interest) ** ((-1) * @total_month)
	@monthly_payment = @amount * (monthly_interest / math_pow_value)
	@interest_set = Array.new
	@principle_set = Array.new
	@balance_set = Array.new
	@interest_total_set = Array.new

	amount_balance = @amount
	for i in 0..(@total_month - 1)
		interest_value = amount_balance * monthly_interest
		principle_value = @monthly_payment - interest_value
		amount_balance = amount_balance - principle_value
		@interest_set.push(interest_value)
		@principle_set.push(principle_value.round(2))
		@balance_set.push(amount_balance.round(2))
		@interest_total_set.push(@interest_set.inject(:+).round(2))
	end
	 respond_to do |format|
	     format.html { render "report" }
	 end
  end
  def self.currency_format(number_input)
  	ActionController::Base.helpers.number_to_currency(number_input ,precision: 2,unit: '')
  end
  private
		def loan_params
			params.require(:loan).permit(:amount, :year, :interest)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loan_helper.rb
module LoanHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoanApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loans/_form.html.erb
<div class="container-fluid">
<%= form_tag("/loan/loan_action", method: "post", id: 'loan_form', remote: true) do %>
<div class="row">
	<div class="col-sm-1 col-sm-offset-1">
		<%= label_tag(:amount, 'Amount ') %>
	</div>
	<div class="col-sm-3">
		<div class="form-group">
    		<div class="input-group">
    			<div class="input-group-addon">
    				&#xe3f;
    			</div>
    			<%= number_field_tag(:amount,nil,placeholder: 'Enter amount value',  class: 'form-control') %>
    		</div>
    	</div>
    </div>
</div>
<div class="row">
	<div class="col-sm-1 col-sm-offset-1">
		<%= label_tag(:year, 'Year(s) ') %>	
	</div>
	<div class="col-sm-3">
		<div class="form-group">
    		<div class="input-group">
    			<%= number_field_tag(:year,nil,class: 'form-control') %>
    			<div class="input-group-addon">
    				Years
    			</div>
    		</div>
    	</div>
    </div>
</div>
<div class="row">
    <div class="col-sm-1 col-sm-offset-1">
		<%= label_tag(:interest, 'Interest ') %>
	</div>
	<div class="col-sm-3">
		<div class="form-group">
    		<div class="input-group">
    			<%= text_field_tag(:interest,3.5,class: 'form-control') %>
    			<div class="input-group-addon">
    				%
    			</div>
    		</div>
    	</div>
    </div>
</div>
<div class="row">
	<div class="col-sm-1 col-sm-offset-1">
		<%= submit_tag("Submit",class: 'btn btn-success') %>
	</div>
</div>
<% end %>
</div>
<div id="results"></div>

app/views/loans/_form_data.html.erb
<div class="container-fluid">
<%= form_for @loan do |f| %>
<div class="row">
	<div class="col-sm-1 col-sm-offset-1">
		<%= f.label :amount %>
	</div>
	<div class="col-sm-3">
		<div class="form-group">
    		<div class="input-group">
    			<div class="input-group-addon">
    				&#xe3f;
    			</div>
    			<%= f.number_field :amount, :placeholder => 'Enter amount value', :class => 'form-control', :step => 1 %>
    		</div>
    	</div>
    </div>
</div>
<div class="row">
	<div class="col-sm-1 col-sm-offset-1">
		<%= f.label :year, 'Year(s) ' %>	
	</div>
	<div class="col-sm-3">
		<div class="form-group">
    		<div class="input-group">
    			<%= f.number_field :year, :class => 'form-control', :step => 1 %>
    			<div class="input-group-addon">
    				Years
    			</div>
    		</div>
    	</div>
    </div>
</div>
<div class="row">
    <div class="col-sm-1 col-sm-offset-1">
		<%= f.label :interest, 'Interest ' %>
	</div>
	<div class="col-sm-3">
		<div class="form-group">
    		<div class="input-group">
    			<%= f.text_field :interest,:value => 3.5,:class => 'form-control' %>
    			<div class="input-group-addon">
    				%
    			</div>
    		</div>
    	</div>
    </div>
</div>
<div class="row">
	<div class="col-sm-1 col-sm-offset-1">
		<%= f.submit "Submit",class: 'btn btn-success' %>
	</div>
</div>
<% end %>
</div>
<div id="results"></div>

app/views/loans/_report.html.erb
<div class="container">
	<div class="well">
		<p><strong>Amount : </strong> <%= @amount %></p>
		<p><strong>Year : </strong> <%= @year %> Years</p>
		<p><strong>Interest : </strong> <%= @interest %> %</p>
	</div>
<table class="table table-hover">
	<tr>
		<th>Month/Year</th>
		<th>Payment</th>
		<th>Principle Paid</th>
		<th>Interest Paid</th>
		<th>Total Interest</th>
		<th>Balance</th>
	</tr>
	<% date = DateTime.now.to_date %>
	<% Date::DATE_FORMATS[:month_and_year] = '%b / %Y' %>
	<% for i in 0..(@total_month - 1) %>
		<tr>
			<td><%= date.to_formatted_s(:month_and_year)  %></td>
			<td><%= LoansController.currency_format(@monthly_payment.round(2)) %></td>
			<td><%= LoansController.currency_format(@principle_set[i]) %></td>
			<td><%= LoansController.currency_format(@interest_set[i]) %></td>
			<td><%= LoansController.currency_format(@interest_total_set[i]) %></td>
			<td><%= LoansController.currency_format(@balance_set[i]) %></td>
		</tr>
		<% date = date.to_time.advance(:months => 1).to_date %>
	<% end %>
</table>
</div>

app/views/loans/edit.html.erb
<%= render 'form_data' %>

app/views/loans/index.html.erb
<%= link_to 'New loan', new_loan_path %>
<table class="table">
		<tr>
			<th>id</th>
			<th>amount</th>
			<th>year</th>
			<th>interest</th>
			<th>view detail</th>
			<th>edit</th>
			<th>destroy</th>
		</tr>
	<% @loans.each do |l|%>
		<tr>
			<td><%= l.id %></td>
			<td><%= l.amount %></td>
			<td><%= l.year %></td>
			<td><%= l.interest %></td>
			<td><%= link_to 'View', loan_path(l) %></td>
			<td><%= link_to 'Edit', edit_loan_path(l) %></td>
       		<td><%= link_to 'Destroy', loan_path(l),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
	
</table>

app/views/loans/new.html.erb
<%= render 'form_data' %>

app/views/loans/report.html.erb
<%= render 'report' %>